name: ti4_objectives
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^1.0.3
  rxdart: ^0.23.1
  uuid: any
  sticky_headers: ^0.1.4
  after_init: ^0.1.2
  provider: any
  path_provider:
  moor_ffi:
    git:
      url: git@github.com:simolus3/moor.git
      ref: develop
      path: moor_ffi
  reorderables:
    git:
      url: git://github.com/hanshengchiu/reorderables.git
  sliver_animated_list: any
  async: ^2.2.0
  grpc:
    path: ../grpc-dart
  protobuf: ^1.0.1

dev_dependencies:
  build_runner:
  moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      ref: develop
      path: moor_generator

dependency_overrides:
  moor:
    git:
      url: git@github.com:simolus3/moor.git
      ref: develop
      path: moor
  sqlparser:
    git:
      url: git@github.com:simolus3/moor.git
      ref: develop
      path: sqlparser
  flutter_launcher_name: any


flutter_launcher_name:
  name: "TI4 Objectives"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
